#-- Project Information
site_name: 'HarmoFinder Docs'
site_description: 'Official Documentation for the HarmoFinder Bot.'
site_author: 'The HarmoFinder Team'
site_url: 'https://docs.harmofinder.ai'

#-- Repository
repo_name: 'HarmoFinder/docs'
repo_url: 'https://github.com/HarmoFinder/docs'
edit_uri: 'edit/main/docs/'

#-- Theme & Appearance
theme:
  name: 'material'
  palette:
    # Palette toggle for light vs dark mode
    - scheme: default
      primary: 'indigo'
      accent: 'indigo'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: 'black'
      accent: 'indigo'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  icon:
    repo: fontawesome/brands/github-alt

#-- Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

#-- Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: timeago

#-- Extra Features
extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  feedback:
    title: Was this page helpful?
    ratings:
      - icon: "ðŸ˜ž"
        name: "Not helpful"
        data: 0
        note: "Thanks for your feedback! We'll use it to improve this page."
      - icon: "ðŸ˜Š"
        name: "Helpful"
        data: 1
        note: "Thanks for your feedback!"

#-- Navigation Structure
nav:
  - 'Home': 'index.md'
  - 'Freemium Journey':
    - 'Getting Started': 'getting_started.md'
    - 'Core Concepts':
      - 'Pattern vs. Signal': 'core_concepts/pattern_vs_signal.md'
      - 'The Confidence Score': 'core_concepts/confidence_score.md'
  - 'Pro Journey':
    - 'Trader''s Cookbook':
      - 'Backtesting Signals': 'pro_journey/cookbook/backtesting_python.md'
      - 'Risk Management': 'pro_journey/cookbook/risk_management.md'
  - 'Quant Journey':
    - 'API Reference':
      - 'Data Endpoints': 'quant_journey/api/data_endpoints.md'
      - 'Data Models': 'quant_journey/api/data_models.md'
  - 'Resources':
    - 'Alpha Glossary': 'resources/alpha_glossary.md'
  - 'Legal':
    - 'Risk Disclaimer': 'legal/risk_disclaimer.md'
